AllCops:
  Exclude:
    - 'Rakefile'
    - 'Gemfile'
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/seeds.rb'
    - 'test/test_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
Documentation:
  Enabled: false